// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duiqqscnftxsycmjeihf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aXFxc2NuZnR4c3ljbWplaWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODU3NTQsImV4cCI6MjA3MDU2MTc1NH0.kIeg2uzuRQc7XiblNR7FR-o-NHnVLFmZYSNFct1zVow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});